StockMarketApp/stockMarket-WebPortal/src/main/java/stock/vista/vector/CotizacionesMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.vista.vector;

import com.xtaticzero.systems.base.constants.excepcion.impl.BusinessException;
import com.xtaticzero.systems.base.constants.excepcion.impl.FrontException;
import com.xtaticzero.systems.base.dto.CotizacionDiariaDTO;
import com.xtaticzero.systems.base.dto.CotizacionHistoricoDTO;
import com.xtaticzero.systems.base.dto.CotizacionPromedioDTO;
import com.xtaticzero.systems.base.dto.IPCDto;
import com.xtaticzero.systems.base.util.FechaUtil;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.RowEditEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.UploadedFile;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import stock.vista.CotizacionAbstractMB;

/**
 *
 * @author Ing. Emmanuel Estrada Gonzalez <emmanuel.estradag.ipn@gmail.com>
 */
@Controller("cotizacionesMB")
//@Scope(value = "session")
@Scope(value = "view")
public class CotizacionesMB extends CotizacionAbstractMB {

    private static final long serialVersionUID = 1406891739814666634L;

    protected static String ATTRIB_YEAR_FILTER = "ATTRIB_YEAR_FILTER";
    protected static int MAX_OF_YEAR = 20;

    @PostConstruct
    public void init() throws FrontException, BusinessException, IOException {

        validateUsuarioValido();
        setCotizacionBO(getCotizacionService().getBOCotizacion(getUsuario()));
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/plantillas/CargaIPCPlantilla.xlsx");
        setPlantilla(new DefaultStreamedContent(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "layoutIPC.xlsx"));
        InputStream stream2 = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/plantillas/CargaCotizacionDiariaPlantilla.xlsx");
        setPlantillaCotDiaria(new DefaultStreamedContent(stream2, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "layoutCotizacionDiaria.xlsx"));
        setCotizacionBO(getCotizacionService().getLstIPC(getCotizacionBO(), 0));
        getCotizacionService().getLstCotizaciones(getCotizacionBO());
        getCotizacionBO().setLstHistoricoCotizacion(new ArrayList<CotizacionHistoricoDTO>());
        setLstIndiceCotizacion(getCotizacionBO().getLstIpc());
        getCotizacionBO().setNewIPC(new IPCDto());
        
        setExistencias(new ArrayList());
        setUtilidades(new ArrayList());
        setLstCotizacionDTO(new ArrayList());
        setLstCotizacionAcciones(new ArrayList());
        

        try {
            if (((Integer) getAttributeSession(ATTRIB_YEAR_FILTER)) != null) {
                setYearFilter(((Integer) getAttributeSession(ATTRIB_YEAR_FILTER)));
                getCotizacionBO().setYearFiltro(getYearFilter());
                getCotizacionService().calcularPromediosAnuales(getCotizacionBO(), FechaUtil.getCurrentYear());
            } else {
                getCotizacionBO().setYearFiltro(-1);
                getCotizacionService().calcularPromediosAnuales(getCotizacionBO(), FechaUtil.getCurrentYear());
            }
        } catch (Exception e) {
            logger.error(e);
            FacesMessage message = new FacesMessage(getMessageResourceString("msj.err.carga.datos"));
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

    }

    public void handleFileUpload(FileUploadEvent event) {
        try {

            UploadedFile fileExcel = event.getFile();

            getCotizacionService().insertIPCFromExcel(getCotizacionBO(), null, fileExcel.getInputstream());
            setCotizacionBO(getCotizacionService().getLstIPC(getCotizacionBO(), 0));
            setLstIndiceCotizacion(getCotizacionBO().getLstIpc());

            FacesMessage message = new FacesMessage(getMessageResourceString("msj.exito.carga.excel"), event.getFile().getFileName());
            FacesContext.getCurrentInstance().addMessage(null, message);
        } catch (Exception e) {
            logger.error(e);
            FacesMessage message = new FacesMessage(getMessageResourceString("msj.err.carga.excel"));
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

    }

    public void handleFileUploadCotizacion(FileUploadEvent event) {
        try {

            UploadedFile fileExcel = event.getFile();

            getCotizacionService().getLstCotizacionesFromExcel(getCotizacionBO(), fileExcel.getInputstream());
            getCotizacionService().insertLstCotizacionesFromExcel(getCotizacionBO());
            getCotizacionService().getLstCotizaciones(getCotizacionBO());

            try {
                if (((Integer) getAttributeSession(ATTRIB_YEAR_FILTER)) != null) {
                    setYearFilter(((Integer) getAttributeSession(ATTRIB_YEAR_FILTER)));
                    getCotizacionBO().setYearFiltro(getYearFilter());
                    getCotizacionService().calcularPromediosAnuales(getCotizacionBO(), getCotizacionBO().getYearFiltro());
                } else {
                    getCotizacionBO().setYearFiltro(-1);
                    getCotizacionService().calcularPromediosAnuales(getCotizacionBO(), FechaUtil.getCurrentYear());
                }
            } catch (Exception e) {
                logger.error(e);

            }

            FacesMessage message = new FacesMessage(getMessageResourceString("msj.exito.carga.excel"), event.getFile().getFileName());
            FacesContext.getCurrentInstance().addMessage(null, message);
        } catch (Exception e) {
            logger.error(e);
            FacesMessage message = new FacesMessage(getMessageResourceString("msj.err.carga.excel"));
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

    }

    public void onRowEdit(RowEditEvent event) {
        FacesMessage msg = new FacesMessage("Cotizacion Editada", ((CotizacionDiariaDTO) event.getObject()).getEmisora().getNombre());
        FacesContext.getCurrentInstance().addMessage(null, msg);

        try {
            getCotizacionBO().setCotizacionSeleccionada(((CotizacionDiariaDTO) event.getObject()));
            getCotizacionService().actualizarCotizacion(getCotizacionBO());
            getCotizacionService().getLstCotizaciones(getCotizacionBO());
        } catch (Exception e) {
            logger.error(e);
            msgError(e.getMessage());
        }
    }

    public void buscarHistorialCotizacion() {
        if (getCotizacionBO().getCotizacionSeleccionada() != null) {
            try {
                getCotizacionService().findCotizacionDiariaHistoricoByEmisora(getCotizacionBO());
            } catch (BusinessException ex) {
                getCotizacionBO().setLstHistoricoCotizacion(new ArrayList<CotizacionHistoricoDTO>());
                logger.error(ex.getMessage(), ex);
            }
        }
    }

    public void onRowCancel(RowEditEvent event) {
        try {
            getCotizacionService().getLstCotizaciones(getCotizacionBO());
        } catch (Exception e) {
            logger.error(e);
            msgError(e.getMessage());
        }
    }

    public List<Integer> getLstComboYears() {
        try {
            getCotizacionService().getLstOfYearsHistory(getCotizacionBO());
            return getCotizacionBO().getLstYearsHistorico() == null ? new ArrayList<Integer>() : getCotizacionBO().getLstYearsHistorico();
        } catch (Exception e) {
            logger.error(e);
            msgError(e.getMessage());
            return new ArrayList<>();
        }
    }

    public void processAverage() {
        if (getCotizacionBO().getYearFiltro() != null) {
            int currenteYear = FechaUtil.getCurrentYear();
            setAttributeSession(ATTRIB_YEAR_FILTER, getCotizacionBO().getYearFiltro());
            //Procesar y sacar promedio
            try {
                getCotizacionService().calcularPromediosAnuales(getCotizacionBO(), currenteYear);
            } catch (Exception e) {
                logger.error(e);
                msgError(e.getMessage());
            }

        } else {
            deletAttributeSession(ATTRIB_YEAR_FILTER);
        }
    }

    public String getNombreEmisoraById(int id) {
        if (getCotizacionBO().getLstCotizacionesDiarias() != null && !getCotizacionBO().getLstCotizacionesDiarias().isEmpty()) {
            List<CotizacionDiariaDTO> response = getCotizacionBO().getLstCotizacionesDiarias();

            if (response != null) {
                for (CotizacionDiariaDTO cotizacion : response) {
                    if (cotizacion.getEmisora().getEmisora_id().intValue() == id) {
                        return cotizacion.getEmisora().getNombre();
                    }
                }
            }

        }

        return "";
    }

    public int getLastYear() {
        return FechaUtil.getCurrentYear() - 1;
    }

    public CotizacionPromedioDTO getCotizacionPromedio(int id) {
        return getCotizacionBO().getMapCotizacionPromedio().get(new BigInteger(String.valueOf(id)));
    }

    public void insertNewIPC(){
        try {
            getCotizacionService().insertNewIPC(getCotizacionBO());
            getCotizacionBO().setIpcNew(new IPCDto());
            getCotizacionService().getLstIPC(getCotizacionBO(), 0);

StockMarketApp/stockMarket-WebPortal/src/main/java/stock/vista/vector/EstadoMensualMB.java
package stock.vista.vector;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.mat.tabacos.vista.AbstractManagedBean;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import stock.market.dto.Fondo;

/**
 *
 * @author Alejandro Hernandez
 */
@Controller("estadoMensualMB")
@Scope(value = "view")
public class EstadoMensualMB extends AbstractManagedBean {

    private List<Fondo> fondos;
    private List<Fondo> fondos2;

    @PostConstruct
    public void init() {
        fondos = new ArrayList<>();                
        for (int i = 1; i <= 9; i++) {
            Fondo fondo = getFactory().manufacturePojo(Fondo.class);
            fondos.add(fondo);
        }
        
        fondos2 = new ArrayList<>();                
        for (int i = 1; i <= 9; i++) {
            Fondo fondo = getFactory().manufacturePojo(Fondo.class);
            fondos2.add(fondo);
        }

    }

    public List<Fondo> getFondos() {
        return fondos;
    }

    public List<Fondo> getFondos2() {
        return fondos2;
    }

    
}

StockMarketApp/stockMarket-WebPortal/src/main/java/stock/vista/vector/HorizontalMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.vista.vector;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.mat.tabacos.vista.AbstractManagedBean;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import stock.horizontal.dto.ExistenciaInicial;
import stock.horizontal.dto.Utilidad;

/**
 *
 * @author Juan
 */
@Controller("horizontalMB")
@Scope(value = "view")
public class HorizontalMB extends AbstractManagedBean {

    private DecimalFormat df = new DecimalFormat("#.00");
    private List<ExistenciaInicial> existencias;
    private List<Utilidad> utilidades;

    @PostConstruct
    public void init() {
        existencias = new ArrayList<>();
        utilidades = new ArrayList<>();

        for (int i = 1; i <= 9; i++) {
            ExistenciaInicial existencia = getFactory().manufacturePojo(ExistenciaInicial.class);
            existencia.setEmisora("Emisora " + i);
            existencias.add(existencia);
        }

        for (int i = 1; i <= 9; i++) {
            Utilidad utilidad = getFactory().manufacturePojo(Utilidad.class);
            utilidad.setEmisora("Emisora " + i);
            utilidades.add(utilidad);
        }

    }

    public Integer getSumaAccionesExistencias() {
        int suma = 0;
        for (ExistenciaInicial exis : existencias) {
            suma += exis.getAcciones();
        }
        return suma;
    }

    public String getSumaImportesExistencias() {
        double suma = 0.0;
        for (ExistenciaInicial exis : existencias) {
            suma += exis.getImporte();
        }
        return df.format(suma);
    }

    public Integer getSumaAccionesUtilidades() {
        int suma = 0;
        for (Utilidad util : utilidades) {
            suma += util.getAcciones();
        }
        return suma;
    }

    public String getSumaImportesUtilidades() {
        double suma = 0.0;
        for (Utilidad util : utilidades) {
            suma += util.getImporte();
        }
        return df.format(suma);
    }

    public List<ExistenciaInicial> getExistencias() {
        return existencias;
    }

    public List<Utilidad> getUtilidades() {
        return utilidades;
    }

}

StockMarketApp/stockMarket-WebPortal/src/main/java/stock/vista/vector/SimuladorMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.vista.vector;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.mat.tabacos.vista.AbstractManagedBean;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import stock.horizontal.dto.Accion;
import stock.horizontal.dto.Capa;

/**
 *
 * @author Juan
 */
@Controller("simuladorMB")
@Scope(value = "view")
public class SimuladorMB extends AbstractManagedBean {

    private static final long serialVersionUID = -4699717909755577329L;

    private List<Capa> capas;
    private List<Capa> selectedCapas;

    @PostConstruct
    public void init() {
        capas = new ArrayList<>();
        List<Accion> acciones = new ArrayList<>();

        Accion accion1 = new Accion();
        accion1.setId("CEMEX_1_1");
        accion1.setFecha(new Date());
        accion1.setCompra(5);
        accion1.setVenta(0);
        accion1.setPrecioCompra(10.00);
        accion1.setImporte(accion1.getCompra() * accion1.getPrecioCompra());
        accion1.setCostoUnitario(9.80);
        accion1.setCostoTotal(accion1.getCompra() * accion1.getCostoUnitario());
        accion1.setUtilidad(accion1.getImporte() - accion1.getCostoTotal());
        accion1.setPorcentajeVenta(accion1.getUtilidad() / accion1.getImporte());

        acciones.add(accion1);

        Capa capa1 = new Capa();
        capa1.setId("CEMEX_1_1");
        capa1.setAcciones(acciones);

        Capa capa2 = new Capa();
        capa2.setId("CEMEX_2_1");
        capa2.setAcciones(acciones);

        capas.add(capa1);
        capas.add(capa2);

    }

    public List<Capa> getCapas() {
        return capas;
    }

    public void setCapas(List<Capa> capas) {
        this.capas = capas;
    }

    public List<Capa> getSelectedCapas() {
        return selectedCapas;
    }

    public void setSelectedCapas(List<Capa> selectedCapas) {
        this.selectedCapas = selectedCapas;
    }

}

StockMarketApp/stockMarket-WebPortal/src/main/java/stock/vista/vector/SimuladorNewMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.vista.vector;

import com.xtaticzero.systems.base.constants.excepcion.impl.BusinessException;
import com.xtaticzero.systems.base.constants.excepcion.impl.FrontException;
import javax.annotation.PostConstruct;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import stock.vista.VistaAbstractMB;

/**
 *
 * @author Ing. Emmanuel Estrada Gonzalez <emmanuel.estradag.ipn@gmail.com>
 */
@Controller("simuladorNewMB")
@Scope(value = "view")
public class SimuladorNewMB extends VistaAbstractMB {

    private static final long serialVersionUID = -7154330566109088617L;

    @PostConstruct
    public void init() throws FrontException, BusinessException {
        validateUsuarioValido();
    }

}

StockMarketApp/stockMarket-WebPortal/src/main/webapp/pages/stockMarket/horizontal.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:pe="http://primefaces.org/ui/extensions">
    <html>
        <h:head>
        </h:head>
        <h:body>
            <ui:include src="../background.xhtml"/>
            <ui:include src="menuHeader.xhtml"/>
            <div id="panelCentral" 
                 style="position: absolute;
                 top: 80px;
                 height: 200px;
                 /*                 border: 3px solid #73AD21;*/
                 align-content: center;
                 width: 1533.0px;
                 margin-left:auto;
                 margin-right:auto;">

                <h:form>
                    <h:panelGrid>
                        <div style="font-size: x-large;">
                            <h1>Horizontal</h1> 
                        </div>                        
                        <div style="font-size: small;">
                            <h2>Fondo - Resumen De Operaciones del: 01-ene-18 al: 19-abr-18</h2>
                        </div>                        

                    </h:panelGrid>
                    <p:tabView scrollable="true">
                        <p:tab title="Existencia Inicial" >
                            <p:dataTable value="#{horizontalMB.existencias}" var="existencia">
                                <p:column headerText=""> 
                                    <h:outputText value="#{existencia.emisora}" />
                                </p:column>
                                <p:column headerText="Acciones"> 
                                    <h:outputText value="#{existencia.acciones}"  style="float:right"/>
                                </p:column>
                                <p:column headerText="Costo De Adquisiciones"> 
                                    <h:outputText value="#{existencia.costoAdquisicion}"  style="float:right"/>
                                </p:column>
                                <p:column headerText="Importe"> 
                                    <h:outputText value="#{existencia.importe}"  style="float:right"/>
                                </p:column>
                                <p:columnGroup type="footer">
                                    <p:row>
                                        <p:column footerText="Total:" style="text-align:right"/>
                                        <p:column footerText="#{horizontalMB.sumaAccionesExistencias}" style="text-align:right"/>
                                        <p:column />
                                        <p:column footerText="#{horizontalMB.sumaImportesExistencias}" style="text-align:right" />
                                    </p:row>
                                </p:columnGroup>
                            </p:dataTable> 
                        </p:tab>
                        <p:tab title="Utilidad (Perdida) Por Realizar">
                            <p:dataTable value="#{horizontalMB.utilidades}" var="utilidad">
                                <p:column headerText=""> 
                                    <h:outputText value="#{utilidad.emisora}" style="float:none"/>
                                </p:column>
                                <p:column headerText="Acciones"> 
                                    <h:outputText value="#{utilidad.acciones}"  style="float:right"/>
                                </p:column>
                                <p:column headerText="Utilidad Por Accion"> 
                                    <h:outputText value="#{utilidad.utilidadXAccion}"  style="float:right"/>
                                </p:column>
                                <p:column headerText="Importe"> 
                                    <h:outputText value="#{utilidad.importe}"  style="float:right"/>
                                </p:column>
                                <p:columnGroup type="footer">
                                    <p:row>
                                        <p:column footerText="Total:" style="text-align:right"/>
                                        <p:column footerText="#{horizontalMB.sumaAccionesUtilidades}" style="text-align:right"/>
                                        <p:column />
                                        <p:column footerText="#{horizontalMB.sumaImportesUtilidades}" style="text-align:right" />
                                    </p:row>
                                </p:columnGroup>
                            </p:dataTable>     
                        </p:tab>
                        <p:tab title="Existencia Inicial A Valor De Mercado">
                            Tabla    
                        </p:tab>
                        <p:tab title="Compras">
                            Tabla    
                        </p:tab>
                        <p:tab title="Ventas">
                            Tabla    
                        </p:tab>
                        <p:tab title="Costo De Ventas">
                            Tabla    
                        </p:tab>
                        <p:tab title="Utilidad (Perdida) Realizada">
                            Tabla    
                        </p:tab>
                        <p:tab title="Existencia A Costo De Adquisicion">
                            Tabla    
                        </p:tab>
                        <p:tab title="Existencia A Valor De Mercado">
                            Tabla    
                        </p:tab>
                        <p:tab title="Utilidad (Perdida) Por Realizar">
                            Tabla    
                        </p:tab>
                        <p:tab title="Utilidad (Perdida) Neta">
                            Tabla    
                        </p:tab>
                    </p:tabView>
                </h:form>
            </div>
        </h:body>
    </html>
</f:view>

StockMarketApp/stockMarket-WebPortal/src/main/webapp/pages/stockMarket/menuHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:pe="http://primefaces.org/ui/extensions">

    <!-- HEADER -->
    <div id="header" class="ui-g-12 ui-md-12">
        <p:breadCrumb>
            <p:menuitem value="Página de inicio" url="paginaInicio.jsf" />
            <p:menuitem value="Cotizaciones" url="cotizaciones.jsf" />
            <p:menuitem value="Simulador" url="simulador.jsf" />
            <p:menuitem value="Movimientos" url="movimientos.jsf" />            
        </p:breadCrumb>
<!--        <p:breadCrumb>
            <p:menuitem value="Página de inicio" url="paginaInicio.jsf" />
            <p:menuitem value="Cotizaciones" url="cotizaciones.jsf" />
            <p:menuitem value="Simulador" url="simulador.jsf" />
            <p:menuitem value="Movimientos" url="movimientos.jsf" />
            <p:menuitem value="Estado Mensual" url="estadoMensual.jsf" />
            <p:menuitem value="Horizontal" url="horizontal.jsf" />
            <p:menuitem value="Órdenes" url="ordenes.jsf" />
            <p:menuitem value="Cotización de Acciones" url="vector.jsf" />
        </p:breadCrumb>-->
    </div>
</f:view>

StockMarketApp/stockMarket-WebPortal/src/main/webapp/pages/stockMarket/newSimulador.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" >
    <html>
        <h:head>
        </h:head>
        <h:body>
            <ui:include src="../background.xhtml"/>
            <ui:include src="menuHeader.xhtml"/>
            <div id="panelCentral" 
                 style="position: absolute;
                 top: 75px;
                 height: 200px;
                 /*                 border: 3px solid #73AD21;*/
                 align-content: center;
                 width: 1533.0px;
                 margin-left:auto;
                 margin-right:auto;">
                <h:form>
                    <p:growl id="msgs" showDetail="true" autoUpdate="true"/>
                    <f:event listener="#{simuladorNewMB.preRender}" type="preRenderView" />                    
                    
                </h:form>
            </div>
        </h:body>
    </html>
</f:view>

StockMarketApp/stockMarket-WebPortal/src/main/webapp/pages/stockMarket/ordenes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:pe="http://primefaces.org/ui/extensions">
    <html>
        <h:head>
            <style>
                .redColor{
                    background-color:red!important;
                    background-image:none!important;
                }

                .bluesColor{
                    background-color: blue!important;
                    background-image:none!important;
                }
                .moradoColor{
                    background-color: blueviolet!important;
                    background-image:none!important;
                }
                .brounColor{
                    background-color: #FC0!important;
                    background-image:none!important;
                }
            </style>
        </h:head>
        <h:body>
            <ui:include src="../background.xhtml"/>
            <ui:include src="menuHeader.xhtml"/>
            <div id="panelCentral" 
                 style="position: absolute;
                 top: 75px;
                 height: 200px;
                 /*                 border: 3px solid #73AD21;*/
                 align-content: center;
                 width: 1533.0px;
                 margin-left:auto;
                 margin-right:auto;">

                <h:form>
                    <p:panel style="width: 1090.0px;
                             margin-left:auto;
                             margin-right:auto;">
                        <h:panelGrid columns="1">
                            <p:dataTable var="car" 
                                         value="#{estatusOrdenesMB.lstCotizacionDTO}" 
                                         rowStyleClass="#{car.porcentaje le 20 ? 'redColor' : car.porcentaje le 40? 'bluesColor': car.porcentaje le 70? 'moradoColor': null}"
                                         paginator="true"
                                         rows="10"
                                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                         rowsPerPageTemplate="5,10,15,50"
                                         style="width: 1050px">
                                <p:column headerText="Folio">
                                    <h:outputText value="#{car.id}" />
                                </p:column>

                                <p:column headerText="Emisora">
                                    <h:outputText value="#{car.emisora}" />
                                </p:column>

                                <p:column headerText="Origen">
                                    <h:outputText value="#{car.nombreAccion}" />
                                </p:column>

                                <p:column headerText="Instrucción">
                                    <h:outputText value="#{car.importe}" />
                                </p:column>
                            </p:dataTable>
                            <h:panelGroup>
                                <p:commandLink action="#{estatusOrdenesMB.btnImprimirAcuse}" ajax="false" immediate="true">
                                    <h:graphicImage value="/resources/images/pdf.png" />
                                </p:commandLink>
                            </h:panelGroup>
                        </h:panelGrid>
                    </p:panel>
                </h:form>
            </div>
        </h:body>
    </html>
</f:view>

StockMarketApp/stockMarket-WebPortal/src/main/webapp/pages/stockMarket/statusLoad.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:pe="http://primefaces.org/ui/extensions">

    <p:ajaxStatus onstart="PF('statusDialog').show();" onsuccess="PF('statusDialog').hide();"/>

    
    <p:dialog modal="true" header="#{msj['titulo.panel.espere']}" draggable="false" closable="false"
              resizable="false" id="statusDialog" widgetVar="statusDialog">
        <p:graphicImage value="/resources/images/ajaxloadingbar.gif"/>
    </p:dialog>
</f:view>